#!/bin/bash

## #ddev-generated
## Description: Provides additional setup routines after composer project is installed
## Usage: ibexa-post-setup
## Example: ddev ibexa-post-setup

source .ddev/commands/host/.utils

[ -z "$SETTINGS_FILE" ] && SETTINGS_FILE="./.ddev/.ibexa-instance-settings"
[ -z "$PROVISION_FILE_GENERAL" ] && PROVISION_FILE_GENERAL="./.ddev/.ibexa-setup-general-provisioned"
[ -z "$PROVISION_FILE_SERVICES" ] && PROVISION_FILE_SERVICES="./.ddev/.ibexa-setup-services-provisioned"
[ -z "$VERBOSE_INSTALL" ] && VERBOSE_INSTALL=false
[ -z "$PROVISION_FILE_POST_SETUP" ] && PROVISION_FILE_POST_SETUP="./.ddev/.ibexa-setup-post-provisioned"

if [ -f "$PROVISION_FILE_POST_SETUP" ]; then
  # Nothing to do
  exit 0
fi

if [ "$VERBOSE_INSTALL" != false ]; then
    clear
fi

if [ ! -f "$SETTINGS_FILE" ] || [ ! -f "$PROVISION_FILE_GENERAL" ] || [ ! -f "$PROVISION_FILE_SERVICES" ]; then
    echo "Setup not finished. Run this command after executing ibexa-setup."
    exit 1
fi

source $SETTINGS_FILE

# todo

touch "$PROVISION_FILE_POST_SETUP"
ddev restart
