type: php
composer_version: "2"
nodejs_version: "18"
router_http_port: "80"
router_https_port: "443"
docroot: "public/"
use_dns_when_possible: true
additional_hostnames: []
additional_fqdns: []
xdebug_enabled: false
upload_dirs:
    - var/storage
web_environment:
    - VERBOSE_INSTALL=false # set to `true` to view verbose output during install
hooks:
    post-start:
        - exec-host: "ddev ibexa-configurator"
        - exec-host: "ddev ibexa-setup"
        - exec-host: "ddev ibexa-installer"
